/**
 * What every diagnostic code means, in one line each.
 *
 * There was no such list. 76 of the 131 codes the processor emits
 * appeared in no document at all, four codes the spec named were never
 * emitted, and two more were documented under a name the code does not
 * use (`CT_RATIO_UNSPECIFIED` for `CT_RATIO_MISSING`,
 * `MISSING_SEQUENCE_DATA` for `SEQUENCE_DATA_MISSING`) -- so a reader
 * looking one up found either nothing or the wrong thing.
 *
 * The gloss lives *here*, beside the code, rather than in a document
 * that has to be remembered: `spec/sections/diagnostics.adoc` is
 * generated from this table by `scripts/sync-diagnostics.mjs`, and
 * `tests/unit/diagnostics.spec.ts` holds the two sets equal in both
 * directions. A new code with no entry fails the build; an entry for a
 * code nothing emits fails it too.
 *
 * The gloss says what the finding *is*, not what to do about it -- the
 * emitted message carries the specifics and usually the remedy. Keep
 * them to one sentence.
 */

/** How serious a finding is where it is emitted. */
export type Severity = 'error' | 'warning' | 'info';

export interface DiagnosticInfo {
  /**
   * Severity as emitted. A few codes are raised at more than one
   * severity depending on where the check sits; those list both, most
   * serious first.
   */
  severity: Severity[];
  /** One sentence: what the finding is. */
  gloss: string;
}

export const DIAGNOSTICS: Readonly<Record<string, DiagnosticInfo>> = {
  /* ---- lexing and parsing ---------------------------------------- */
  UNEXPECTED_CHARACTER: { severity: ['error'],
    gloss: 'A character the lexer does not recognise anywhere in the language.' },
  UNTERMINATED_STRING: { severity: ['error'],
    gloss: 'A quoted string reaches the end of the line without closing.' },
  UNTERMINATED_BLOCK_COMMENT: { severity: ['error'],
    gloss: 'A `/* ... */` comment reaches the end of the file without closing.' },
  EXPECTED_TOKEN: { severity: ['error'],
    gloss: 'A specific token was required here and something else was found.' },
  EXPECTED_IDENT: { severity: ['error'],
    gloss: 'An identifier was required here -- a block id, or a key.' },
  EXPECTED_KEYWORD: { severity: ['error'],
    gloss: 'A keyword from a closed set was required and the word given is not in it.' },
  EXPECTED_LBRACE: { severity: ['error'],
    gloss: 'A block was expected to open with `{`.' },
  EXPECTED_NUMBER: { severity: ['error'],
    gloss: 'A number was required and the value given is not one.' },
  EXPECTED_TOP_LEVEL: { severity: ['error'],
    gloss: 'A top-level block was expected at this point in the file.' },
  UNKNOWN_TOP_LEVEL: { severity: ['error'],
    gloss: 'A top-level block whose keyword the language does not have.' },
  TOPLEVEL_PARSE: { severity: ['error'],
    gloss: 'A top-level block could not be parsed; its contents are skipped.' },
  MISSING_VALUE: { severity: ['error'],
    gloss: 'A key was written with `=` and no value after it.' },
  DUPLICATE_KEY: { severity: ['error'],
    gloss: 'One key written twice in a block, where the second would silently win.' },
  NESTED_BLOCK_SCOPED: { severity: ['error'],
    gloss: 'A block appears inside another that does not contain it.' },

  /* ---- keys and values ------------------------------------------- */
  UNKNOWN_SETTING: { severity: ['error'],
    gloss: 'A key the block does not accept, in a block where every key changes a number.' },
  UNKNOWN_KEY: { severity: ['warning'],
    gloss: 'A key that means something elsewhere in the language, written in the wrong block.' },
  RENAMED_KEY: { severity: ['error'],
    gloss: 'A key that has been renamed; the message names the current spelling.' },
  REMOVED_KEY: { severity: ['error'],
    gloss: 'A key that has been removed; the message says what it was and what to do instead.' },
  VALUE_UNKNOWN: { severity: ['error'],
    gloss: 'A value outside the closed set the key accepts.' },
  PAGE_VALUE_UNKNOWN: { severity: ['error'],
    gloss: 'A `page` styling value outside the set that key accepts.' },
  UNIT_MISSING: { severity: ['error'],
    gloss: 'A physical quantity written as a bare number; no key carries its own unit.' },
  UNIT_UNKNOWN: { severity: ['error'],
    gloss: 'A unit suffix the language does not recognise, such as `KA` for `kA`.' },
  UNIT_WRONG_QUANTITY: { severity: ['error'],
    gloss: 'A real unit of the wrong kind, such as a time suffix on a current.' },

  /* ---- system, voltages and transformers ------------------------- */
  VOLTAGE_UNKNOWN: { severity: ['error'],
    gloss: 'A reference to a voltage level `system.voltages` does not declare.' },
  VOLTAGE_LEVEL_INVALID: { severity: ['error'],
    gloss: 'A declared voltage level whose magnitude is not a positive number.' },
  VOLTAGE_RATIO_UNRESOLVED: { severity: ['error'],
    gloss: 'Two levels a current has to cross, with no ratio derivable between them.' },
  VECTOR_GROUP_MISSING: { severity: ['error'],
    gloss: 'A declared transformer with no `vector_group`, which is what settles a referral.' },
  VECTOR_GROUP_UNREADABLE: { severity: ['error'],
    gloss: 'A `vector_group` string that cannot be read in full, such as `Dyn11 (assumed)`.' },
  REFERRAL_NEEDS_CONNECTION: { severity: ['error'],
    gloss: 'An unbalanced fault carried across a transformer whose windings do not settle how.' },

  /* ---- relays, elements and stages ------------------------------- */
  RELAY_VOLTAGE_UNSPECIFIED: { severity: ['warning'],
    gloss: 'A relay with no `voltage` in a study that declares more than one level.' },
  CT_RATIO_MISSING: { severity: ['error'],
    gloss: 'A setting in secondary amps on a relay with no `ct_ratio` to convert it.' },
  CT_RATIO_INVALID: { severity: ['error'],
    gloss: 'A `ct_ratio` that is not a positive ratio.' },
  CT_SPREAD_WIDE: { severity: ['warning'],
    gloss: 'CT ratios on one sheet differing by more than 5:1, which a secondary axis cannot serve.' },
  DUPLICATE_ELEMENT: { severity: ['error'],
    gloss: 'Two elements of one relay sharing an id.' },
  ELEMENT_NO_CURVE: { severity: ['error'],
    gloss: 'An element with no curve producer: no `curve`, `formula`, `flex_points` or stages.' },
  ELEMENT_MIXED_FORMS: { severity: ['error'],
    gloss: 'An element carrying both the shorthand curve form and a `stages` block.' },
  ELEMENT_EMPTY_STAGES: { severity: ['error'],
    gloss: 'A `stages` block with no stages in it.' },
  STAGE_NO_CURVE: { severity: ['error'],
    gloss: 'A stage with no curve producer of its own and none to inherit.' },
  CURVE_UNKNOWN: { severity: ['error'],
    gloss: 'A `curve` id not in the constants table; the message suggests the closest.' },
  TMS_MISSING: { severity: ['error'],
    gloss: 'A dependent-time curve with no multiplier, which is never defaulted to 1.' },
  TMS_OUT_OF_RANGE: { severity: ['error'],
    gloss: 'A multiplier outside the range of the dial that curve is set in.' },
  DEFINITE_NO_DELAY: { severity: ['warning'],
    gloss: 'A definite-time stage with no `t_delay`, which draws as instantaneous.' },
  DEFINITE_WITH_TMS: { severity: ['error'],
    gloss: 'A `tms` on a definite-time stage, whose time does not scale.' },
  ZERO_DELAY_NOT_PLOTTABLE: { severity: ['warning'],
    gloss: 'A `t_delay` of zero, which has no position on a logarithmic time axis.' },
  PICKUP_MISSING: { severity: ['error'],
    gloss: 'A stage with no `I_pickup`, so it has no multiple to evaluate.' },
  PICKUP_NOT_POSITIVE: { severity: ['error'],
    gloss: 'An `I_pickup` that is zero or negative.' },
  PICKUP_TOO_LOW_FOR_VOLTAGE: { severity: ['warning'],
    gloss: 'A pickup so far below the level current that a unit error is the likely cause.' },
  CURRENT_PCT_OUT_OF_RANGE: { severity: ['error'],
    gloss: 'A `share` outside `(0, 100]`.' },
  SHARE_DECLARED_TWICE: { severity: ['warning'],
    gloss: 'A share stated both on the element and by a scenario, where the scenario wins.' },
  MEASURES_REQUIRED: { severity: ['error'],
    gloss: 'A sequence element that does not say which current its pickup is in.' },
  MEASURES_UNKNOWN: { severity: ['error'],
    gloss: 'A `measures` value that is not one of the quantities.' },
  MEASURES_MIXED: { severity: ['error'],
    gloss: 'Stages of one element measuring different currents, so it is not one characteristic.' },
  FORMULA_K_INVALID: { severity: ['error'],
    gloss: 'A user formula whose `k` is not positive.' },
  FORMULA_C_INVALID: { severity: ['error'],
    gloss: 'A user formula whose `c` is negative.' },
  FORMULA_ALPHA_INVALID: { severity: ['error'],
    gloss: 'A user formula whose `alpha` is not positive.' },
  FLEX_TOO_FEW_POINTS: { severity: ['error'],
    gloss: 'A piecewise table with fewer than two points, which defines no curve.' },
  FLEX_NOT_MONOTONE: { severity: ['error'],
    gloss: 'A piecewise table with two times at one current, leaving the curve undefined there.' },
  FLEX_TIME_NOT_POSITIVE: { severity: ['warning'],
    gloss: 'A piecewise table point whose time is zero or negative.' },
  CURVE_STYLE_INVALID: { severity: ['error'],
    gloss: 'A per-curve `style` outside solid, dashed and dotted.' },
  CURVE_WIDTH_INVALID: { severity: ['error'],
    gloss: 'A per-curve `width_px` that is not a positive number.' },

  /* ---- devices ---------------------------------------------------- */
  DEVICE_NO_KIND: { severity: ['error'],
    gloss: 'A device that does not say what sort of thing it is.' },
  DEVICE_NO_CURVE: { severity: ['error'],
    gloss: 'A device with no table and no clearing time, so it has no curve to draw.' },

  /* ---- faults, scenarios and points ------------------------------- */
  DUPLICATE_FAULT: { severity: ['error'],
    gloss: 'Two faults sharing an id, where the later would silently replace the earlier.' },
  DUPLICATE_SCENARIO: { severity: ['error'],
    gloss: 'Two scenarios sharing an id.' },
  DUPLICATE_TIME: { severity: ['error'],
    gloss: 'Two required-clearance entries sharing an id.' },
  DUPLICATE_POINT: { severity: ['error'],
    gloss: 'Two marked points sharing an id.' },
  FAULT_CURRENT_INVALID: { severity: ['error'],
    gloss: 'A declared fault current that is not finite and positive.' },
  FAULT_RANGE_INVERTED: { severity: ['error'],
    gloss: 'A fault whose minimum is above its maximum.' },
  FAULT_SINGLE_POINT: { severity: ['info'],
    gloss: 'A fault stating one current, so its range endpoints default to it.' },
  FAULT_VOLTAGE_UNSPECIFIED: { severity: ['error'],
    gloss: 'A fault with no voltage level in a study that declares several.' },
  RANGE_WITHOUT_CENTRE: { severity: ['error'],
    gloss: 'A component range declared with no centre value, so the two come from different sources.' },
  RANGE_INCOMPLETE: { severity: ['error'],
    gloss: 'One end of a component range declared without the other.' },
  SEQUENCE_RESIDUAL_CONFLICT: { severity: ['error'],
    gloss: 'A condition declaring both `I0` and `residual` where the residual is not three times `I0`.' },
  SEQUENCE_DATA_MISSING: { severity: ['error'],
    gloss: 'An element measures a component the condition neither declares nor has a type to derive.' },
  SEQUENCE_ACROSS_LEVELS: { severity: ['error'],
    gloss: 'A zero-sequence quantity that would have to cross a transformer that blocks it.' },
  SCENARIO_NO_LEVELS: { severity: ['error'],
    gloss: 'A scenario with no `level` block, so no relay can be evaluated against it.' },
  SCENARIO_LEVEL_MISSING: { severity: ['error'],
    gloss: 'A scenario that says nothing at the level a graded relay sits on.' },
  POINT_CURRENT_INVALID: { severity: ['error'],
    gloss: 'A marked point with no current, or one that is not positive.' },
  POINT_CURRENT_AND_CONDITION: { severity: ['error'],
    gloss: 'A marked point stating its own current and naming a condition; they are alternatives.' },
  POINT_TIME_INVALID: { severity: ['error'],
    gloss: 'A marked point whose time is not positive.' },
  TIME_INVALID: { severity: ['error'],
    gloss: 'A required-clearance entry whose time is not positive.' },
  DUPLICATE_RATING: { severity: ['error'],
    gloss: 'Two `currents` ratings sharing an id.' },
  RATING_CURRENT_INVALID: { severity: ['error'],
    gloss: 'A `currents` rating whose declared current is not finite and positive.' },

  /* ---- grading and the solver ------------------------------------- */
  DUPLICATE_GRADE: { severity: ['error'],
    gloss: 'The same primary and backup graded twice at the same condition.' },
  GRADE_MISSING_SIDE: { severity: ['error'],
    gloss: 'A grade naming only one of its two sides.' },
  GRADE_SELF_PAIR: { severity: ['error'],
    gloss: 'A grade whose primary and backup are the same element.' },
  GRADE_ON_COMBINE: { severity: ['error'],
    gloss: 'A grade naming a synthetic `combine` curve, which is not a relay.' },
  GRADE_FAULT_AND_SCENARIO: { severity: ['error'],
    gloss: 'A grade naming both a `fault` and a `scenario`; they are alternatives.' },
  GRADE_MIXED_QUANTITY: { severity: ['warning'],
    gloss: 'A pair whose two sides measure different currents at the same condition.' },
  GRADE_BEYOND_CUTOFF: { severity: ['error'],
    gloss: 'A margin asked for past the current where one side\'s curve stops.' },
  FAULT_OPTIONAL_NO_GRADE_CHECK: { severity: ['warning'],
    gloss: 'A grade with no condition: the curves render but no margin is computed.' },
  NO_OPERATION: { severity: ['warning'],
    gloss: 'Neither side operates at the condition given, so there is no margin.' },
  MARGIN_BELOW_CTI: { severity: ['error'],
    gloss: 'A `margin_target` below the `margin` floor it is supposed to clear.' },
  MARGIN_NO_SOLVE: { severity: ['warning'],
    gloss: 'A `margin_target` with no `solve` block, so it is reported as a target only.' },
  MARGIN_FROM_DERIVED_COMPONENT: { severity: ['warning'],
    gloss: 'A margin resting on a component derived from an assumed fault shape.' },
  TOLERANCE_OUT_OF_RANGE: { severity: ['error'],
    gloss: 'A `tolerance_pct` outside a sensible band.' },
  UPSTREAM_TO_INVALID: { severity: ['error'],
    gloss: 'An `upstream_to` ceiling that is not a positive current.' },
  UPSTREAM_RANGE_EMPTY: { severity: ['warning'],
    gloss: 'An upstream sweep whose ceiling is not above the declared fault.' },
  UPSTREAM_WITHOUT_CTI: { severity: ['warning'],
    gloss: 'An upstream sweep with no margin constraint for it to check against.' },
  UPSTREAM_DISABLED_WITH_CEILING: { severity: ['warning'],
    gloss: 'An `upstream_to` ceiling on a pair whose sweep is switched off.' },
  SOLVE_WITHOUT_TARGET: { severity: ['error'],
    gloss: 'A `solve` block with neither `margin_target` nor `margin` to aim at.' },
  SOLVE_FREE_UNKNOWN: { severity: ['error'],
    gloss: 'A `free` variable the solver cannot vary.' },
  SOLVE_OVERRODE_SETTING: { severity: ['warning'],
    gloss: 'A solved dial replacing one declared in the file; the sheet is drawn at the solved value.' },
  SOLVE_SUPERSEDED: { severity: ['warning'],
    gloss: 'Another grade\'s constraint on the same stage demanded more and set the dial.' },
  SOLVER_NO_TARGET: { severity: ['warning'],
    gloss: 'The solver was given no finite margin to aim at.' },
  SOLVER_NO_IDMT_STAGE: { severity: ['warning'],
    gloss: 'The controlling stage is definite-time and has no multiplier to turn.' },
  SOLVER_NO_PRIMARY_OPERATION: { severity: ['warning'],
    gloss: 'The primary does not operate at the fault, so there is nothing to grade against.' },
  SOLVER_READONLY_DEVICE: { severity: ['warning'],
    gloss: 'The backup is a device, whose published curve is not adjustable.' },
  SOLVER_UNSATISFIABLE: { severity: ['warning'],
    gloss: 'The target needs a dial outside the settable range; the report says how far.' },
  MULTISTAGE_MULTIVAR_SOLVE: { severity: ['warning'],
    gloss: 'Two free variables on a multi-stage backup, which v1 does not solve.' },

  /* ---- combines --------------------------------------------------- */
  COMBINE_NO_SOURCES: { severity: ['error'],
    gloss: 'A combine with an empty source list.' },
  COMBINE_CHAINED: { severity: ['error'],
    gloss: 'A combine whose source is another combine; synthetic curves do not chain.' },
  COMBINE_LEVEL_AMBIGUOUS: { severity: ['error'],
    gloss: 'A combine drawing on two voltage levels without saying which bus it is read at.' },
  COMBINE_UNKNOWN_VOLTAGE: { severity: ['error'],
    gloss: 'A combine `voltage` naming a level `system.voltages` does not declare.' },

  /* ---- annotations and spans -------------------------------------- */
  ANNOTATE_NO_POSITION: { severity: ['error'],
    gloss: 'An annotation that says where to point but not where to put the label.' },
  ANNOTATE_CURRENT_AND_CONDITION: { severity: ['error'],
    gloss: 'An annotation stating its own current and naming a condition; they are alternatives.' },
  ANNOTATE_QUANTITY_MISMATCH: { severity: ['error'],
    gloss: 'An annotation whose declared component is not one the annotated element measures.' },
  ANNOTATE_STYLE_UNKNOWN: { severity: ['error'],
    gloss: 'An annotation `style` outside the set that key accepts.' },
  ANNOTATE_LABEL_NOT_DRAWN: { severity: ['warning'],
    gloss: 'A label on a `pin`, which draws a marker only, so the text would not appear.' },
  SPAN_NO_ANCHOR: { severity: ['error'],
    gloss: 'A span with no curve, point or condition at either end.' },
  SPAN_INCOMPLETE: { severity: ['error'],
    gloss: 'A span with only one of its two ends.' },
  SPAN_EMPTY: { severity: ['warning'],
    gloss: 'A span whose two ends are the same figure, so it has no extent.' },
  SPAN_MIXED_QUANTITIES: { severity: ['error'],
    gloss: 'A span between a current and a time, which are not on one axis.' },

  /* ---- views, pages and scoping ----------------------------------- */
  VIEW_RANGE_INVERTED: { severity: ['error'],
    gloss: 'A view whose axis minimum is at or above its maximum.' },
  SECOND_AXIS_SAME_LEVEL: { severity: ['warning'],
    gloss: 'A second axis in the level the sheet is already drawn in, so both scales agree.' },
  PAGE_SIZE_UNKNOWN: { severity: ['error'],
    gloss: 'A paper keyword the processor does not have.' },
  PAGE_SIZE_INCOMPLETE: { severity: ['error'],
    gloss: 'A custom sheet giving only one of `width_mm` and `height_mm`.' },
  PAGE_MARGIN_NEGATIVE: { severity: ['error'],
    gloss: 'A negative paper margin.' },
  PAGE_SCALE_INVERTED: { severity: ['error'],
    gloss: 'A manual axis scale whose minimum is at or above its maximum.' },
  WATERMARK_ON_FINAL: { severity: ['warning'],
    gloss: 'A draft watermark on a study whose revision reads as issued.' },
  UNRESOLVED_REFERENCE: { severity: ['error'],
    gloss: 'A reference to a relay, element, device or condition the study does not declare.' },
  UNRESOLVED_STAGE: { severity: ['error'],
    gloss: 'A reference to a stage the named element does not have.' },
  UNRESOLVED_VIEW: { severity: ['error'],
    gloss: 'A `views` scope naming a sheet the study does not declare.' },
  UNRESOLVED_GROUP: { severity: ['error'],
    gloss: 'A reference to a group the study does not declare.' },
  UNRESOLVED_GROUP_MEMBER: { severity: ['error'],
    gloss: 'A group naming a member the study does not declare.' },
};

/** Every code the processor documents, sorted. */
export function allDiagnosticCodes(): string[] {
  return Object.keys(DIAGNOSTICS).sort();
}
