/**
 * Every code the processor emits is documented, and nothing else is.
 *
 * There was no diagnostic-code reference anywhere in the set. 76 of the
 * 131 emitted codes appeared in no document; four codes the spec named
 * were never emitted; and two were documented under a name the code
 * does not use -- `CT_RATIO_UNSPECIFIED` for `CT_RATIO_MISSING`,
 * `MISSING_SEQUENCE_DATA` for `SEQUENCE_DATA_MISSING` -- so a reader
 * looking one up found either nothing or the wrong thing.
 *
 * The list cannot be kept by hand, which is how it got into that
 * state. This holds `DIAGNOSTICS` equal to what the source actually
 * emits, in *both* directions: a new code with no entry fails, and an
 * entry for a code nothing emits fails too.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { DIAGNOSTICS, allDiagnosticCodes } from '@tc/constants/diagnostics';

const repoRoot = (): string => process.cwd();

const sources = (dir: string, out: string[] = []): string[] => {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) sources(p, out);
    else if (p.endsWith('.ts')) out.push(p);
  }
  return out;
};

/**
 * Codes the source actually raises.
 *
 * Both shapes: `add(ctx, 'CODE', 'severity', ...)` in the validator,
 * and a `code: 'CODE'` property in the parser, the grader and the
 * solver. The registry itself is excluded -- it is the list being
 * checked, not a source of emissions.
 */
const emitted = (): Set<string> => {
  const found = new Set<string>();
  for (const file of sources(join(repoRoot(), 'src'))) {
    if (file.endsWith(join('constants', 'diagnostics.ts'))) continue;
    const text = readFileSync(file, 'utf8');
    for (const m of text.matchAll(/add\((?:ctx|[a-z]+),\s*'([A-Z][A-Z_0-9]+)'/g)) found.add(m[1]);
    /*
     * `code:` takes a literal, or a ternary picking between two --
     * `code: isTypo ? 'UNKNOWN_SETTING' : 'UNKNOWN_KEY'`. Both arms
     * count: each is a code the processor can raise.
     */
    for (const m of text.matchAll(/code:\s*([^,\n}]+)/g)) {
      for (const lit of m[1].matchAll(/'([A-Z][A-Z_0-9]+)'/g)) found.add(lit[1]);
    }
  }
  return found;
};

describe('the diagnostic-code registry', () => {
  it('has an entry for every code the source emits', () => {
    const missing = [...emitted()].filter((c) => !(c in DIAGNOSTICS)).sort();
    expect(missing, 'emitted but not in DIAGNOSTICS').toEqual([]);
  });

  it('has no entry for a code nothing emits', () => {
    /*
     * The other direction, and the one that let four phantom codes sit
     * in the spec for months. A code that is documented and never
     * raised sends a reader looking for a check that does not exist.
     */
    const raised = emitted();
    const stale = allDiagnosticCodes().filter((c) => !raised.has(c));
    expect(stale, 'in DIAGNOSTICS but never emitted').toEqual([]);
  });

  it('carries a real sentence for each, not a restatement of the name', () => {
    for (const [code, info] of Object.entries(DIAGNOSTICS)) {
      expect(info.gloss.length, `${code} needs a gloss`).toBeGreaterThan(20);
      expect(info.gloss.endsWith('.'), `${code} gloss should be a sentence`).toBe(true);
      /*
       * `TMS_OUT_OF_RANGE: "tms out of range"` says nothing. A gloss
       * may well use the code's own words -- they are the subject --
       * but it has to say more than the name already does.
       */
      const spelt = code.toLowerCase().replace(/_/g, ' ');
      expect(info.gloss.toLowerCase().replace(/[^a-z ]/g, '').trim(),
        `${code} gloss merely respells the code`).not.toBe(spelt);
      expect(info.gloss.length, `${code} gloss should say more than its name`)
        .toBeGreaterThan(code.length);
      expect(info.severity.length, `${code} needs a severity`).toBeGreaterThan(0);
    }
  });
});

describe('the generated reference', () => {
  const doc = readFileSync(
    join(repoRoot(), 'spec', 'sections', 'diagnostics.adoc'), 'utf8');

  it('lists every code', () => {
    const missing = allDiagnosticCodes().filter((c) => !doc.includes(`\`${c}\``));
    expect(missing, 'in DIAGNOSTICS but not in the generated section').toEqual([]);
  });

  it('is regenerated, not hand-edited', () => {
    expect(doc).toMatch(/generated by `scripts\/sync-diagnostics\.mjs`/);
  });
});

describe('the rest of the documentation', () => {
  const specDir = join(repoRoot(), 'spec', 'sections');
  /*
   * `diagnostics.adoc` is the generated list itself, and
   * `revision-history.adoc` records what codes *used* to be called --
   * `CT_RATIO_UNSPECIFIED` appears there on purpose, as the mistake
   * being recorded. Everything else is prose describing the processor
   * as it is, and may only name codes it has.
   */
  const prose = readdirSync(specDir)
    .filter((f) => f.endsWith('.adoc')
      && f !== 'diagnostics.adoc' && f !== 'revision-history.adoc')
    .map((f) => readFileSync(join(specDir, f), 'utf8'))
    .join('\n')
    + readFileSync(join(repoRoot(), 'docs', 'guide.adoc'), 'utf8')
    + readFileSync(join(repoRoot(), 'docs', 'api.adoc'), 'utf8');

  it('names no code the processor does not have', () => {
    /*
     * Catches the drift that produced `CT_RATIO_UNSPECIFIED` and
     * `MISSING_SEQUENCE_DATA`: a plausible name, written once, never
     * emitted, and repeated between documents thereafter.
     *
     * Only backtick-quoted upper-snake words are considered, and only
     * those long enough to be a code rather than a relay id.
     */
    const named = new Set(
      [...prose.matchAll(/`([A-Z][A-Z_0-9]{8,})`/g)].map((m) => m[1]),
    );
    /* Words in that shape that are deliberately not codes. */
    const notCodes = new Set([
      'DEFAULT_PAGE_MARGIN_MM', 'TMS_RANGE_ANSI', 'TMS_RANGE_IEC',
      'PER_UNIT_SUFFIXES', 'SECONDARY_SUFFIXES', 'PRIMARY_SUFFIXES',
      'DEFAULT_G_D', 'BOTH_CIRCUITS_IN', 'ONE_CIRCUIT_OUT',
      'LOAD_END_3PH', 'LOAD_END_2PH', 'LOAD_END_2PHE',
      /* Relay ids from worked examples, which share the shape. */
      'R_TRF_INC', 'R_FDR_110', 'R_INC_330',
      /* Named in the note recording what those rules used to claim. */
      'FUSE_CLEARS_BEFORE_RELAY_VIOLATED', 'FUSE_AND_RELAY_BOTH_CURVE_ABOVE_CABLE',
    ]);
    const unknown = [...named]
      .filter((c) => !notCodes.has(c) && !(c in DIAGNOSTICS))
      .sort();
    expect(unknown, 'named in prose but not a diagnostic code').toEqual([]);
  });
});
